#ifndef __stereoCameraParallelViewCmd_h 
#define __stereoCameraParallelViewCmd_h 

//-
// ==========================================================================
// Copyright (C) 1995 - 2006 Autodesk, Inc. and/or its licensors.  All
// rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its
// licensors, which is protected by U.S. and Canadian federal copyright
// law and by international treaties.
//
// The Data is provided for use exclusively by You. You have the right
// to use, modify, and incorporate this Data into other products for
// purposes authorized by the Autodesk software license agreement,
// without fee.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the
// following disclaimer, must be included in all copies of the
// Software, in whole or in part, and all derivative works of
// the Software, unless such copies or derivative works are solely
// in the form of machine-executable object code generated by a
// source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR
// PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR
// TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS LICENSORS
// BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK
// AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY
// OR PROBABILITY OF SUCH DAMAGES.
//
// ==========================================================================
//+

//	File Name: stereoCameraParallelViewCmd.cpp
//	
//	Date: August 05 2002
//
//	Description:
//		Code to test test drawing with multiple cameras in the same view.
//

#include <stereoCameraParallelView.h>

#include <maya/MPxModelEditorCommand.h>

#define kLeftEyeCameraFlag				"-lcm"
#define kLeftEyeCameraFlagLong			"-leftCamera"

#define kRightEyeCameraFlag				"-rcm"
#define kRightEyeCameraFlagLong			"-rightCamera"

#define kCenterCameraFlag				"-ccm" 
#define kCenterCameraFlagLong			"-centerCamera" 

#define kDisplayModeFlag				"-dm" 
#define kDisplayModeFlagLong			"-displayMode" 

//#define kStereoAnaglyphMode				"stereoAnaglyph"
#define kStereoParallelMode				"stereoParallel"
#define kLeftEye						"leftEye" 
#define kRightEye						"rightEye" 
#define kCenterEye						"centerEye" 

//#define kSwapBufferFlag					"-sb" 		
//#define kSwapBufferFlagLong				"-swapBuffers" 
#define kSwapLeftRightEyeFlag			"-slr"
#define kSwapLeftRightEyeFlagLong		"-swapLeftRightEye"

#define kStereoCameraParallelMenuScript	"ccgStereoCameraMenuScript"
#define kStereoParallelViewCmdName		"stereoCameraParallelView"

#define kOverrideAdornmentDrawFlag		"-oa" 
#define kOverrideAdornmentDrawFlagLong	"-overrideAdornment"

#define kOverrideHUDDrawFlag			"-oh"
#define kOverrideHUDDrawFlagLong		"-overrideHUD"

#define kDrawFrameMaskFlag				"-dfm"
#define kDrawFrameMaskFlagLong			"-drawFrameMask"

#define kDeviceRatioFlag				"-dr"
#define kDeviceRatioFlagLong			"-deviceRatio"

#define kLeftLeftMaskFlag					"-llm"
#define kLeftLeftMaskFlagLong				"-leftLeftMask"

#define kLeftRightMaskFlag					"-lrm"
#define kLeftRightMaskFlagLong				"-leftRightMask"

#define kRightLeftMaskFlag					"-rlm"
#define kRightLeftMaskFlagLong				"-rightLeftMask"

#define kRightRightMaskFlag					"-rrm"
#define kRightRightMaskFlagLong				"-rightRightMask"

#define kLeftLeftOffsetFlag					"-llo"
#define kLeftLeftOffsetFlagLong				"-leftLeftOffset"

#define kLeftRightOffsetFlag				"-lro"
#define kLeftRightOffsetFlagLong			"-leftRightOffset"

#define kRightLeftOffsetFlag				"-rlo"
#define kRightLeftOffsetFlagLong			"-rightLeftOffset"

#define kRightRightOffsetFlag				"-rro"
#define kRightRightOffsetFlagLong			"-rightRightOffset"

#define kEnableDiagnoseLineFlag				"-edl"
#define kEnableDiagnoseLineFlagLong			"-enableDiagnoseLine"

class MPx3dModelView;
class MObject;
class MDagPath;

class stereoCameraParallelViewCmd: public MPxModelEditorCommand
{
public:
	typedef MPxModelEditorCommand ParentClass;

								stereoCameraParallelViewCmd();
	virtual						~stereoCameraParallelViewCmd();

	static void*				creator();

	virtual MStatus				doEditFlags();
	virtual MStatus				doQueryFlags();

	virtual MStatus				appendSyntax();
	virtual MString				editorMenuScriptName() const;

	virtual MPx3dModelView*		userView();

private:

	MStatus						getCameraFromString( const MString &, 
													 MDagPath & ); 
	
	static const char*  className();
};

#endif 
